spring.application.name: ${WEATHER_APPLICATION_NAME:weather-app}

weather:
  url: ${WEATHER_URL:https://api.openweathermap.org/data/2.5/weather}
  connect-timeout: ${WEATHER_CONNECTION_TIMEOUT:700}
  read-timeout: ${WEATHER_READ_TIMEOUT:700}
  api-key: ${WEATHER_API_KEY:changeMe}
  timeout-seconds: ${WEATHER_TIMEOUT_SECONDS:5}
  cache-enabled: ${WEATHER_CACHE_ENABLED:true}
  delay-enabled: ${WEATHER_DELAY_ENABLED:true}
  weather-cache-properties:
    duration-in-days:  ${WEATHER_CACHE_DURATION_IN_DAYS:1}
    maximum-size: ${WEATHER_CACHE_MAXIMUM_SIZE:10}
server:
  port: ${WEATHER_SERVER_PORT:9000}
